version: "3"

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./react-webrtc
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - "backend"
